### ISSUE TITLE
Serio,martwy kod.

### ISSUE THREAD

**Issue by oliwex** [sukerberk1/poker-game#10]
https://github.com/sukerberk1/poker-game/blob/df7029dc5e5e927807a0bdbaa42d62d6354b6bf8/card.cpp#L10

**Comment by sukerberk1** [comment]
Fakt, aktualny sposób nie jest idealny. 
Aby zrobić to lepiej można by zrobić Buildera kart, który umożliwiałby tworzenie tylko prawidłowych kart. Może coś takiego zrobimy jak starczy czasu i będę chciał porobić jakis overenginnering na koniec.
A ten sposób... Cóż jeśli karta stworzona, nawet przez literówkę, będzie nieprawidłowa, to cała rozgrywka dalej nie ma sensu - program może operować tylko na prawidłowych kartach.
Stąd walidacja - która w założeniu nigdy nie powinna się pojawić. Możnaby tam dodać loggera np.:
```cpp
std::cout << "Card constructor misuse, program terminates";
```
Ale tak jak napisałem, ten kod nie powinien się wykonać, tymbardziej że (do tej pory) jedyny moment w którym korzystamy z konstruktora jest w klasie `Deck`. I korzystamy tam z `Card::getValidPowers` i `Card::getValidColors` które zabezpieczają nas przed tym ***martwym*** kodem.

Więcej:
https://codeopinion.com/is-an-anemic-domain-model-really-that-bad/?fbclid=IwAR3_NRRXZu9qhplIQ6VMZM0_TJHw5q03EqubikbcOopvG0kSF0o0-CdJJUE

**Comment by sukerberk1** [comment]
Zalepione ✅
