### ISSUE TITLE
No gratuluje, return w środku pętli. A licznik rozkazów na procesorze szaleje.

### ISSUE THREAD

**Issue by oliwex** [sukerberk1/poker-game#11]
https://github.com/sukerberk1/poker-game/blob/df7029dc5e5e927807a0bdbaa42d62d6354b6bf8/card.cpp#L25

**Comment by sukerberk1** [comment]
Bzdura. Kompilator to zoptymalizuje, a jeśli nie to wystarczy kupić nowy procesor 🙌


Source:
https://www.reddit.com/r/AskProgramming/comments/an1fgn/is_using_return_and_break_inside_a_loop/?rdt=39594
https://softwareengineering.stackexchange.com/questions/18454/should-i-return-from-a-function-early-or-use-an-if-statement?fbclid=IwAR3TucJIZSXA0JBb3VwO0pxnDJqsOmb6JLLCh2_h_LuKUsOvBZU6Fp774YU
https://stackoverflow.com/questions/5607762/what-does-code-motion-mean-for-loop-invariant-code-motion
