### ISSUE TITLE
Player

### ISSUE THREAD

**Issue by sukerberk1** [sukerberk1/poker-game#2]
Ma odzwierciedlać gracza. Gracze muszą powstać....

Gracz:
 - ma dwa sloty na dwie karty
 - ma kasę
 - funkcje do zarządzania kartami i żetonami
 
 *Może coś jeszcze ?*
 **Powinniśmy rozważyć czy zasadne jest używanie wskaźników do wskazywania które karty gracz posiada**

**Comment by BigQuadra** [comment]
Biorę gracza... bo musi powstać.
