### ISSUE TITLE
JOPEK XD

### ISSUE THREAD

**Issue by oliwex** [sukerberk1/poker-game#8]
https://github.com/sukerberk1/poker-game/blob/df7029dc5e5e927807a0bdbaa42d62d6354b6bf8/card.cpp#L32

**Comment by sukerberk1** [comment]
To zostanie, bo z tego jest beka

**Comment by sukerberk1** [comment]
albo na koncu zmienic na jester

Albo Juan/Jeronimo. W końcu on też ma imię.
