### ISSUE TITLE
Klasa w klasie

### ISSUE THREAD

**Issue by oliwex** [sukerberk1/poker-game#9]
Lepiej talie kart zaimplementować klasa w klasie.

**Comment by sukerberk1** [comment]
Klasa `Card` będzie używana wskroś całej gry, więc wątpie aby dostawanie się do niej poprzez `Deck` było dobrym pomysłem - o ile chodzi ci o rozwiązanie typu: 
```cpp
class Deck {
    class Card {...}
}
```

Choćby gracz, który ma w ręce 2 karty, nie będzie miał nic wspólnego z całą ich talią.

Jeśli chodzi ci o implementacje pokroju Struktury wewnątrz:
```cpp
class Card {
     class Power {...};
     class Color {...};
};
```
To nie. Darujmy sobie coś takiego.
